config/routes.rb
HackerNews::Application.routes.draw do
  resources :sessions, except: [:destroy] do
    collection do
      delete "destroy"
    end
  end
  resources :users
  resources :comments
  resources :posts

  resources :votes, only: [:create]

end

app/models/ancestry.rb
class Ancestry < ActiveRecord::Base
  belongs_to :ancestor, :class_name => Comment
  belongs_to :descendant, :class_name => Comment
  # attr_accessible :title, :body
end

app/models/comment.rb
# == Schema Information
#
# Table name: comments
#
#  id         :integer          not null, primary key
#  body       :text
#  post_id    :integer
#  parent_id  :integer
#  user_id    :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Comment < ActiveRecord::Base
  attr_accessible :body, :post_id, :parent_id
  belongs_to :post
  belongs_to :parent, :class_name => Comment
  belongs_to :user

  has_many :comments, :foreign_key => "parent_id"
end

app/models/email.rb
# == Schema Information
#
# Table name: emails
#
#  id         :integer          not null, primary key
#  email      :string(255)
#  user_id    :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Email < ActiveRecord::Base
  attr_accessible :email, :user_id

  belongs_to :user
end

app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id         :integer          not null, primary key
#  title      :string(255)
#  url        :string(255)
#  body       :text
#  user_id    :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Post < ActiveRecord::Base
  attr_accessible :title, :body, :url, :user_id
  has_many :comments
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id         :integer          not null, primary key
#  password   :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class User < ActiveRecord::Base
  attr_accessible :password, :emails_attributes

  has_many :emails
  accepts_nested_attributes_for :emails, :reject_if => :all_blank

end

app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :user
  belongs_to :post
  attr_accessible :user_id, :post_id

  validate :one_post_upvote_per_user

  def one_post_upvote_per_user
    unless Vote.where("user_id = ? AND post_id = ?", self.user_id, self.post_id).empty?
      errors[:base] << "Already voted for this post"
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def show
    @comment = Comment.find(params[:id])
    @comments = @comment.post.comments
    @new_comment = Comment.new
    @new_comment.parent_id = @comment.id
    @new_comment.post_id = @comment.post_id
  end

  def create
    @comment = Comment.create!(params[:comment])
    redirect_to post_url(@comment.post)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def new
    @post = Post.new
    @post.user_id = cookies[:current_user]
  end

  def create
    @post = Post.new(params[:post])
    @post.save! # REV What id the save fails?
    redirect_to posts_url
  end

  def index
    @posts = Post.all
    @votes = Vote.new
    @votes.user_id = cookies[:current_user]
  end

  def show
    @post = Post.find(params[:id])
    @comments = @post.comments
    @new_comment = Comment.new
    @new_comment.post_id = @post.id
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    email = Email.find_by_email(params[:email])
    if email && ( email.user.password == params[:password] )
      cookies.permanent[:current_user] = email.user.id
      redirect_to new_session_url
    else
      render :new
    end
  end

  def destroy
    cookies.delete(:current_user)
    redirect_to new_session_url
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
    3.times { @user.emails.build }
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      redirect_to new_session_url
    else
      render :new
    end
  end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController

  def create
    @vote = Vote.create(params[:vote])
    # if @vote.save
    #   Posts.find(params[:vote][:post_id]).points += 1
    # end
    redirect_to posts_url
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper

  def set_url(url)
    if url.scan("http://").empty?
      "http://#{url}"
    else
      return url
    end
  end

  def find_and_order_children(comment)
    children = @comments.select { |comm| comm.parent_id == comment.id }
    children.sort_by { |child| child.created_at }.reverse
  end

  def print_comment_tree
    str = ""
    @comments.select{|comment| comment.parent_id == nil}.each do |top_level|
      indent = 0
      str += print_comment_and_children(top_level, indent)
      str += "<br>"
      #binding.pry
    end
    str.html_safe
  end

  def print_comment_and_children(comment, indent)
    #binding.pry
    html = "<div class='indent_#{indent}'>#{comment.body} | <a href='/comments/#{comment.id}'>link</a></div>"
    # print comment with class indent-#{indent}
    if find_and_order_children(comment).empty?
      # REV Why not do unless if you're not using the if bit?
    else
      find_and_order_children(comment).each do |sub_comment|
        html << print_comment_and_children(sub_comment, indent + 1)
      end
    end
    html
  end

  def print_comment_tree_comment_page
    str = ""
    str += print_comment_and_children(@comment, 0)
    str.html_safe
  end

  def calc_points(post_id)
    Vote.where("post_id = ?", post_id).count
  end

end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/comments/_form.html.erb
<%= form_for @new_comment do |f| %>
  <%= f.label :body, "Body:" %>
  <%= f.text_area :body%>
  <%= f.hidden_field :post_id %>
  <%= f.hidden_field :parent_id %>
  <%= f.submit%>
<% end %>

app/views/comments/show.html.erb
<h3> <%= @comment.body %> </h3>

<%= render :partial => "form"%>

<br>

<%= print_comment_tree_comment_page%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>HackerNews</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= button_to("Logout", sessions_url, :method=> "delete") if cookies[:current_user]%>
<%= yield %>

</body>
</html>

app/views/posts/_comment.html.erb
Hello!

app/views/posts/index.html.erb
<h1>Posts:</h1>

<% @posts.each do |post| %>
  <%= calc_points(post.id)%>
  <%= render :partial => "votes/form", :locals => {:post_id => post.id}%>
  <%= link_to post.title, set_url(post.url) %>
  <%= link_to "discuss", post_url(post) %>
  <br>
  <br>
<% end %>

<%= link_to "Create New Post", new_post_url%>

app/views/posts/new.html.erb
<h1>Create new post</h1>
<%= form_for(@post) do |f| %>
  <%= f.label :title, "Title:" %>
  <%= f.text_field :title %>
  <br>
  <%= f.label :url, "URL:" %>
  <%= f.text_field :url %>
  <br>
  <%= f.hidden_field :user_id %>
  <%= f.submit %>
<% end %>

app/views/posts/show.html.erb
<h1><%= @post.title %></h1>
<br>
<%= render :partial => "/comments/form"%>
<br>
<br>
<%= print_comment_tree %>

app/views/users/new.html.erb
<h1>Create new user</h1>

<%= form_for(@user) do |f| %>
  <%= f.label :password, "Password:" %>
  <%= f.text_field :password %>
  <br>
  <br>
  Enter emails:
  <%= f.fields_for(:emails) do |email_form| %>
  <br>
    <%= email_form.text_field :email %>
  <% end %>
  <br>
  <%= f.submit %>
<% end %>

app/views/votes/_form.html.erb
<%= form_for @votes do |f|%>
<%= f.hidden_field :user_id %>
<%= hidden_field_tag "vote[post_id]", post_id  %>
<%= f.submit "Upvote" %>
<% end %>